language: generic

sudo: required

services:
  - docker

before-install:
  - docker build -t disparate1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true disparate1/docker-react npm run test
